#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1001560047                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : tpg offline                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Voyageons à Genève !

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Rémy Da Costa Faro                                
your_link                                 : https://レミー.みんな
your_city                                 : Geneva                                
email_address                             : remy@レミー.みんな
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : remydcf
github_username                           : remydcf
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Départs, Itinéraires, Info Traffic
    description                           : Tout ce qu'il faut pour bien voyager à Genève avec les transports publics genevois, en une seule application
    fontawesome_icon_name                 : bus
    
  - title                                 : Mode hors-ligne
    description                           : Pas de réseau ? Pas de problèmes ! tpg offline continue de fonctionner et de donner des informations, même en mode avion.
    fontawesome_icon_name                 : globe-europe

  - title                                 : Innovant
    description                           : Mode sombre, rappels intelligents, notifications des perturbations, histoire des lignes
    fontawesome_icon_name                 : lightbulb

  - title                                 : Apple Watch
    description                           : Une extension pour l'Apple Watch est aussi disponible
    fontawesome_icon_name                 : clock

  - title                                 : Android (bientôt)
    description                           : Avis aux amateurs du robot vert, tpg offline arrive bientôt sur le Play Store !
    fontawesome_icon_name                 : google-play
  
  - title                                 : Et de prochaines nouveautés
    description                           : tpg offline est aussi une application active, open-source et de prochaines nouveautés devrait bientôt arriver !
    fontawesome_icon_name                 : rocket


# Theme Settings
topbar_color                              : "#ff9966"
topbar_transparency                       : 0.1
topbar_title_color                        : "#fff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#6666ff"

app_title_color                           : "#fff"
app_price_color                           : "#eee"
app_description_color                     : "#eee"

feature_title_color                       : "#1a2a3a"
feature_text_color                        : "#2a3a4a"

feature_icons_foreground_color            : "#fff"
feature_icons_background_color            : "#1a2a3a"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown